# Changes here will be overwritten by Copier
_commit: 0.10.14
_src_path: gh:pawamoy/copier-pdm
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2020'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
project_description: Run a command, print its output only if it fails.
project_name: failprint
python_package_command_line_name: failprint
python_package_distribution_name: failprint
python_package_import_name: failprint
repository_name: failprint
repository_namespace: pawamoy
repository_provider: github.com
use_precommit: false

