site_name: "failprint"
site_description: "Run a command, print its output only if it fails."
site_url: "https://pawamoy.github.io/failprint"
repo_url: "https://github.com/pawamoy/failprint"
repo_name: "pawamoy/failprint"
site_dir: "site"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Code Reference:
  - capture.py: reference/capture.md
  - cli.py: reference/cli.md
  - formats.py: reference/formats.md
  - process.py: reference/process.md
  - runners.py: reference/runners.md
  - types.py: reference/types.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    watch:
    - src/failprint
- macros:
    module_name: docs/macros
