site_name: "failprint"
site_description: "Run a command, print its output only if it fails."
site_url: "https://pawamoy.github.io/failprint"
repo_url: "https://github.com/pawamoy/failprint"
repo_name: "pawamoy/failprint"

nav:
  - Overview: index.md
  - Reference:
    - cli.py: reference/cli.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/failprint
