[tool.poetry]
name = "woof"
version = "0.1.0"
description = ""
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
packages = [ { include = "woof", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "^3.8"
ansimarkup = "^1.4.0"
jinja2 = "^2.11.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
woof = "woof.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
