blank_issues_enabled: false
contact_links:
- name: I have a question / I need help
  url: https://github.com/pawamoy/failprint/discussions/new?category=q-a
  about: Please ask and answer questions here.
